version: '2'
services:
  drupal-server:
    container_name: drupal-server
    image: cbiit-drupal
    build: ./
    ports:
     - "8080:80"
    environment:
      hash_salt: $hash_salt
      database: $database
      username: $username
      password: $password
      host: $host
      port: $port
      namespace: $namespace
      driver: $driver
