version: "3"
services:
    db:
        image: mariadb
        restart: always
        environment:
           MYSQL_USER: drupal
           MYSQL_PASSWORD: drupal
           MYSQL_ROOT_PASSWORD: my-secret-pw
           MYSQL_DATABASE: eventsreg
        ports: 
            - "3306:3306"
        networks:
            app_net:
                ipv4_address: 172.16.238.10            
    webeventsreg:
        build: .
        depends_on:
          - db
        container_name: drupal
        environment:
            MYSQL_DATABASE: eventsreg
            MYSQL_HOST: 172.16.238.10
            MYSQL_USER: drupal
            MYSQL_PASSWORD: drupal
            MYSQL_ROOT_PASSWORD: drupal
        ports:
            - "8080:80"
        networks:
            app_net:
                ipv4_address: 172.16.238.11
        volumes:
            - ~/docker_volumes/eventsreg:/local/drupal
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24      
